### PR TITLE
Master

### PR DESCRIPTION
**Pull request by lconcha**
Changes proposed in this pull request:
- Add scan name to output of `brkraw info`
- Set output file names of `brkraw tonii` to include the scan name

Reason:
Makes it easier to recognize several acquisition with the same sequence name.

To do:
- Have the GUI also construct similar output file names.

PS: First pull request in my life!

@BrkRaw/Bruker

### CODE REVIEW

**Comment by gdevenyi** [comment]
This looks good to me, one question, will it ever be the case we don't have a scan name?

**Comment by lconcha** [comment]
Unlikely. The user would have to expressly delete the scan name Paravision's scan list. But not impossible. Perhaps if scan name is empty it could take the sequence name?

**Comment by dvm-shlee** [comment]
Thank you for your pull request and sorry that it took a too long time to merge!
I finally got some time to focus on this project so will make more better community that everyone can contribute this protocol with some documents,

**Comment by lconcha** [comment]
Fantastic, glad you liked the suggestions. Makes me happy that my first ever pull request was accepted!

Thanks for all your hard work.

**Pull request merged**
