### PR TITLE
Output None for inexistent parameter

### LINKED ISSUE #100: Current GitHub version fails to process using JSON
@dvm-shlee and @gdevenyi 

I pulled the current master to take advantage of the fixes implemented in #96 but I cannot convert using `bids_convert` and the -j option.  I get:

```
(brkraw038_20221118) [adamraikes@r1u25n1 ifn_gamma_BIDS]$ brkraw bids_convert dicoms nifti/.brkraw/dicominfo_final.csv -o nifti/ -j nifti/.brkraw/dicominf.json 
Inspect input BIDS datasheet...
Converting 20210721_134024_apoemouse_IFN_Y_C1_QA1136_1_155...
Traceback (most recent call last):
  File "/home/u26/adamraikes/.conda/envs/brkraw038_20221118/bin/brkraw", line 8, in <module>
    sys.exit(main())
  File "/home/u26/adamraikes/.conda/envs/brkraw038_20221118/lib/python3.7/site-packages/brkraw/scripts/brkraw.py", line 476, in main
    build_bids_json(dset, row, fname, json_fname, slope=slope, offset=offset)
  File "/home/u26/adamraikes/.conda/envs/brkraw038_20221118/lib/python3.7/site-packages/brkraw/lib/utils.py", line 412, in build_bids_json
    metadata=ref, condition=condition)
  File "/home/u26/adamraikes/.conda/envs/brkraw038_20221118/lib/python3.7/site-packages/brkraw/lib/loader.py", line 548, in save_json
    json_obj = self._parse_json(scan_id, reco_id, metadata)
  File "/home/u26/adamraikes/.conda/envs/brkraw038_20221118/lib/python3.7/site-packages/brkraw/lib/loader.py", line 506, in _parse_json
    val = meta_get_value(v, acqp, method, visu_pars)
  File "/home/u26/adamraikes/.conda/envs/brkraw038_20221118/lib/python3.7/site-packages/brkraw/lib/utils.py", line 170, in meta_get_value
    return meta_check_express(value, acqp, method, visu_pars)
  File "/home/u26/adamraikes/.conda/envs/brkraw038_20221118/lib/python3.7/site-packages/brkraw/lib/utils.py", line 252, in meta_check_express
    exec('{} = {}'.format(k, val))
  File "<string>", line 1, in <module>
NameError: name 'VisuAcqEchoTime' is not defined
```

EDIT: It appears that it's the VisuAcqEchoTime keyword specifically for this dataset. Doing more digging to investigate.

### PR DESCRIPTION
**Pull request by jeremie-fouquet**
Fixes #100.

Changes proposed in this pull request:
- Get `meta_check_source` to output `None` in case of an inexistent parameter
- Equivalent to reverting to the previous behaviour in the case of a B0 map, which was to output the string "Value was not specified" for EchoTime in the json file

@BrkRaw/Bruker

### CODE REVIEW

**Comment by dvm-shlee** [comment]
The object of returning the non-existing parameter is to return original input as the value, so if the input value is not parameter related, it will acting as string. I did not deeply review in this changes, but have you tested whether changing this makes string input became None in output json file?

**Comment by jeremie-fouquet** [comment]
Because of [this line of code](https://github.com/jeremie-fouquet/brkraw/blob/f5d8dab64c9dc9b7486830260ed0654041039e08/brkraw/lib/loader.py#L568), `None` is transformed into the string `'Value was not specified'` before saving the json. Does that answer the question?

**Comment by jeremie-fouquet** [comment]
See also [here](https://github.com/BrkRaw/brkraw/issues/100#issuecomment-1603242909) for more context.

**Comment by dvm-shlee** [comment]
I see your point, but we need to test if the proposed change impacts the hardcoded string in the METADATA_REF. 

I recall there being a specific reason for this function to return a string. For instance, the template is designed to use string values that aren't present in the metadata files by default. For example, in /brkraw/lib/reference.py, the FMRI_META_REF has a key "CogAtlasID" where the value is a common string (URL) rather than a parameter. I'm concerned that the change you suggest might result in this value being labeled as "Value was not specified".

**Comment by jeremie-fouquet** [comment]
Ok, I get what you mean. In the [commit above](https://github.com/BrkRaw/brkraw/pull/119/commits/30c025a4d82ca080c9a19dd175ed0f8addc36423), I suggest a quick fix. It will only assign None to a parameter value when it is still a string within the function `meta_check_express`. I think it addresses your concern; let me know if not. 

At a later time, it might be worth it to reconsider how the logic behind these checks is implemented.

**Comment by dvm-shlee** [comment]
Based on your suggestion, I'll focus on enhancing the logic BIDS converter for better readability and clarity over the next two weeks. I'll go ahead and merge this pull request. Thanks!

**Pull request merged**
