### PR TITLE
add support for MSME / MESE type and further refactor

### LINKED ISSUE #59: [bids convert] add support for MSME / MESE type
currently brkraw can not handle MSME type, and treat it as etc. 
It need to be converted into:
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data

### PR DESCRIPTION
**Pull request by ycAbout**
Fixes #59.
Further improve on #46

Changes proposed in this pull request:
- add support for MSME / MESE type
- fix the error of naming for MSME
- more refactor

Probably I should make it two separate PR. But it just happened this way...

@BrkRaw/Bruker

### CODE REVIEW

**Comment by ycAbout** [comment]
Are we going to review and merge this @dvm-shlee @gdevenyi ?

**Comment by gdevenyi** [comment]
I have to leave the deep code review to @dvm-shlee, but I can comment on the intents of the modification.

Can you please describe what exactly your changes do in terms of operation on these points:
- add support for MSME / MESE type
- fix the error of naming for MSME

What was it before, what is it now, whats the reasoning behind it.

**Comment by ycAbout** [comment]
for add support for MSME / MESE type:
previously MSME type was treated as etc, which will not pass the bids validator because there is not etc.
now I changed it to be MESE type according to bids standard, and will pass the bids validator.

for fix the error of naming for MSME:
previously a part of the naming for MEME type is repeated multiple times in file name where there are more than one MSME file.
now I fixed the bug, so it will pass the validator.

**Comment by dvm-shlee** [comment]
Thanks for the update, the code improved readability. I will merge this pull request. Thanks!

**Pull request merged**
