### PR TITLE
Subject ID: Remove non alphanumeric

### PR DESCRIPTION
**Pull request by banwoomi**
Fixes #.

Changes proposed in this pull request:
-
-
-

@BrkRaw/Bruker

### CODE REVIEW

**Comment by banwoomi** [comment]
Remove non-alphanumeric of subject ID

**Comment by gdevenyi** [comment]
Is removal the right step here, or should it be replace?

I use this instead, which is slightly gentler for replacement.
`re.sub(r"\W+", "_", mystring)`

**Comment by banwoomi** [comment]
> 

Thanks for the suggestion. I modified it, but BIDS rules only allow letters and numbers. So the "_" is removed.

**Comment by gdevenyi** [comment]
Sorry, this will need an update back to your original code, because \W considers "_" valid.

Is there something else we can substitute? Dashes, or periods?
```
\W
Matches any character which is not a word character. This is the opposite of \w. If the ASCII flag is used this becomes the equivalent of [^a-zA-Z0-9_]. If the LOCALE flag is used, matches characters which are neither alphanumeric in the current locale nor the underscore.

```

**Comment by dvm-shlee** [comment]
@gdevenyi Hi I think it is ok since this code will replace any non-alphanumeric character with '_' and at the later step, it will be changed to 'Underscore' using the below function. https://github.com/BrkRaw/brkraw/blob/89d357b74a7589c945a3b8f77692f83a8ee92ee9/brkraw/scripts/brkraw.py#L464

But if you still think we need to revert this change, please let me know!
Need some time to learn all these feature 😆

**Comment by gdevenyi** [comment]
This code:
```
str.replace(r'\W+', '', regex=True)
```

Will only allow [A-z0-9_]. But the BIDS spec only allows `Labels are strings and MUST only consist of letters (lower or upper case) and/or numbers.`

**Comment by dvm-shlee** [comment]
@gdevenyi I just realized that this is actually not necessary code since this will be manually cleared while updating the BIDS sheet. I will check with @banwoomi and revert it after. Thanks!

**Pull request merged**
